services:
    database:
        container_name: mongodb
        image: mongo:latest
        ports:
            - "27017:27017"
        restart: always
        networks:
            - commerce

    server:
        container_name: node-server
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        networks:
            - commerce
        restart: always
        depends_on:
            - database
        env_file:
            - ./server/.env

    client:
        container_name: react-server
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "4173:4173"
        networks:
            - commerce
        depends_on:
            - server
            - database
        restart: always

networks:
    commerce:
